### ISSUE TITLE
trying t get your code to work.

### ISSUE THREAD

**Issue by drforbin** [galacticstudios/Trek52#4]
Hi, I'm running rsts 10.1 and I am trying to get your code to work on both basic-plus and basic plus 2. When I try in basic-plus it seems the matrix operations are not working! 
I get illegal verb for 'mat' operations, and indeed the mat OPS donot seem to work!
Any ideas? Under basic plus2 the mat ops work but when i import it via kermit It seems the interpreter does like to import.
I get alot of lline continue errors. Rstss uses cr lf so understand all that.

please help

**Comment by galacticstudios** [comment]
According to the BASIC Plus manual, the matrix statements are an optional feature and "might not be installed on your system".

**Comment by drforbin** [comment]
Can you send me the manual. How do I install them.
I figured it would be something like that

**Comment by galacticstudios** [comment]
Google for the RSTS BASIC Plus manual.

I don't know where to get the right version of BASIC Plus or how to install it. The RSTS version (6 or 7?) that came with the PiDP-11 worked for me.

**Comment by drforbin** [comment]
Thxs....will basic-plus2 work?

**Comment by galacticstudios** [comment]
I don't know. I've never tried it.

**Comment by drforbin** [comment]
thxs

**Comment by drforbin** [comment]
I got it working

**Comment by galacticstudios** [comment]
Great! How?

**Comment by drforbin** [comment]
Well, the matrix functions have to be enabled during the install of basic/bplus.
So I had to figure out how to reinstall the bplus software package and enable matrix.
Then had to find me a vt52 emulator and it works!
